### ISSUE TITLE
SDXL-turbo?

### ISSUE THREAD

**Issue by cocktailpeanut** [google/style-aligned#13]
This may be a dumb question, but would it be possible to do this with SDXL (or SD) turbo?

Not sure how it would work since turbo models only require one step, and I didn't fully read through the code enough to understand whether this is a feasible thing or not, but just thought I would ask.

If such a thing was possible, it would open doors to all kinds of crazy things.

**Comment by amirhertz** [comment]
We haven't tried it yet. Our method probably won't work in a single step, but maybe several steps are sufficient.
