### ISSUE TITLE
Missing image files still missing

### ISSUE THREAD

**Issue by SoftologyPro** [google/style-aligned#17]
Issue closed too early.  Not fixed yet.

Run demo_stylealigned_controlnet.py
It still complains about a missing train.jpg
Should that just be train.png renamed to train.jpg or is the jpg a depth map?

**Comment by amirhertz** [comment]
Can you please provide the error you get?

demo_stylealigned_controlnet.py was updated together with the missing images, and it now uses train.png

**Comment by SoftologyPro** [comment]
OK, all good now, thanks.
I only upddated the images and not the script.
