### ISSUE TITLE
ModuleNotFoundError: No module named 'sa_handler'

### ISSUE THREAD

**Issue by StableDiffusionHub** [google/style-aligned#3]
When trying to run the colab notebook i get this error

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-9-84fc88669986>](https://localhost:8080/#) in <cell line: 6>()
      4 import torch
      5 import mediapy
----> 6 import sa_handler

ModuleNotFoundError: No module named 'sa_handler'
```

what is sa_handler? how to correctly import it?
thank you

**Comment by a-r-r-o-w** [comment]
You need to have [this](https://github.com/google/style-aligned/blob/main/sa_handler.py) file to import it. Make sure you've cloned or saved the files correctly. It might that you are running the notebook directly without cloning the repo?

**Comment by amirhertz** [comment]
For running on colab, see https://github.com/camenduru/style-aligned-colab
