### ISSUE TITLE
missing "./example_image/sun.png" for style_aligned_w_controlnet.ipynb

### ISSUE THREAD

**Issue by jerryrt** [google/style-aligned#4]
Though its content can be found in the paper, the resource is missing in the repository. It will cause the failure for this sample.

**Comment by demiguelm** [comment]
Yep, where is the sun? :)

**Comment by jerryrt** [comment]
In fact, there is quite a few depth images as input in the paper, anyway, for reproduction, I got around this issue by cropping the images from the screenshot of the paper. In the code, the depth image is always resized to 1024, so the actual dimension doesn't matter much here.
